# Generated by Django 3.1.7 on 2021-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0002_auto_20210223_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
