# Generated by Django 3.1.7 on 2021-02-24 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0003_auto_20210223_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
