# Generated by Django 3.1.7 on 2021-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproduct', '0004_auto_20210224_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rotate_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
